DiamondBlockLossChance: 0
CreationWaitTime: 10
Upgrades:
  DamageReduction:
    BasePrize: 10000.0
    RaisingConstant: 2.0
  Unbreakable:
    BasePrize: 10000.0
    RaisingConstant: 2.0
  FireAbsorption:
    BasePrize: 10000.0
    RaisingConstant: 2.0