name: ModularArmor
main: de.manimax3.ModularArmor
version: 1.3.1
description: This plugin makes it possible to add upgrades to your Armor!
softdepend: [Vault]

commands:
   mareload:
     description: Reloads the Config!
     usage: /mar
     aliases: [mar,mreload]
   maupdate:
     description: Updates the YML Files!
     usage: /maupdate [config|localization]
     aliases: [mau,mu]