name: ModularArmor
main: de.manimax3.ModularArmor
version: 1.2
description: Adds a ModularArmor
depend: [ItemNBTAPI, Vault]

commands:
   mareload:
     description: Reloads the Config!
     usage: /mar
     aliases: [mar,mreload]
   maupdate:
     description: Updates the YML Files!
     usage: /maupdate [config|localization]
     aliases: [mau,mu]